index:
    path: /base
    controller: App\Controller\DefaultController::index

connect:
    path: /connexion
    controller: App\Controller\DefaultController::connect

accueil:
    path: /
    controller: App\Controller\AccueilController::index

inscription_choix:
    path: /inscription/choisissez-votre-profil
    controller: App\Controller\InscriptionController::inscription_choix_profil

inscription_pro:
    path: /inscription/inscription-professionnel
    controller: App\Controller\InscriptionController::inscription_pro

inscription_particulier:
    path: /inscription/inscription-toulousain
    controller: App\Controller\InscriptionController::inscription_particulier

inscription_reussite:
    path: /inscription/inscription-reussite
    controller: App\Controller\InscriptionController::inscription_reussite

mentions:
    path: /mentions-legales
    controller: App\Controller\MentionsController::mentions

contact:
    path: /contactez-nous
    controller: App\Controller\ContactController::contact

les_restos :
    path: /les-restos
    controller: App\Controller\MangerController::manger

les_sorties :
    path: /les-sorties
    controller: App\Controller\SortirController::index

les_activites :
    path: /les-activites
    controller: App\Controller\ActivitesController::index

add_restos :
    path : /ajouter-restaurant
    controller: App\Controller\MangerController::add

show_restos :
    path : /consulter-restaurants
    controller: App\Controller\MangerController::show