index:
    path: /base
    controller: App\Controller\DefaultController::index

connect:
    path: /connexion
    controller: App\Controller\DefaultController::connect

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index

inscription_phase1:
    path: /inscription/choisissez-votre-profil
    controller: App\Controller\DefaultController::inscription_choix_profil

mentions:
    path: /mentions_legales
    controller: App\Controller\DefaultController::mentions


contact:
    path: /contactez_nous
    controller: App\Controller\DefaultController::contact

manger :
    path: /manger
    controller: App\Controller\MangerController::manger

sortir :
    path: /sortir
    controller: App\Controller\SortirController::index

activites :
    path: /activites
    controller: App\Controller\ActivitesController::index

