index:
    path: /base
    controller: App\Controller\DefaultController::index

connect:
    path: /connexion
    controller: App\Controller\DefaultController::connect

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index

inscription:
    path: /inscription
    controller: App\Controller\DefaultController::inscription

mentions:
    path: /mentions_legales
    controller: App\Controller\DefaultController::mentions

manger :
    path: /manger
    controller: App\Controller\MangerController::manger