index:
    path: /base
    controller: App\Controller\DefaultController::index

accueil:
    path: /
    controller: App\Controller\AccueilController::index



# Les pages d'inscription -------------------------------------------
inscription_choix:
    path: /inscription/choisissez-votre-profil
    controller: App\Controller\InscriptionController::inscription_choix_profil

inscription_pro:
    path: /inscription/professionnel
    controller: App\Controller\InscriptionController::inscription_pro

inscription_particulier:
    path: /inscription/particulier
    controller: App\Controller\InscriptionController::inscription_particulier

inscription_reussite:
    path: /inscription/inscription-reussite
    controller: App\Controller\InscriptionController::inscription_reussite



# Connexion user
user_profile:
    path: /mon-compte
    controller : App\Controller\UserprofileController::userprofile

connect:
    path: /connexion
    controller: App\Controller\DefaultController::connect

disconnect:
    path: /deconnexion
    controller: App\Controller\DefaultController::disconnect

password_forget:
    path: /password-forget
    controller: App\Controller\DefaultController::PasswordForget

new_password:
    path: /new-password
    controller: App\Controller\DefaultController::NewPassword


# Catégories -------------------------------------------
# Les restaurants --------------------------------------
add_restos:
    path: /ajouter-restaurant
    controller: App\Controller\MangerController::add

show_restos:
    path: /consulter-restaurants
    controller: App\Controller\MangerController::show

avis_restos: 
    path: /avis-restaurant{id} # url d'accès a ma page. Le paramètre {id} est un paramètre get.
    controller: App\Controller\MangerController::avisResto
    requirements: 
      id: '\d+' # veut dire que le paramètre id n'acceptera que des chiffres

# Les sorties -----------------------------------------
add_sortie:
    path: /ajouter-sortie
    controller: App\Controller\SortirController::add

show_sorties:
    path: /consulter-sorties
    controller: App\Controller\SortirController::show

avis_sorties: 
    path: /avis-sortie{id} # url d'accès a ma page. Le paramètre {id} est un paramètre get.
    controller: App\Controller\SortirController::avisSortie
    requirements: 
      id: '\d+' # veut dire que le paramètre id n'acceptera que des chiffres

# Les activités -----------------------------------------
add_activity:
    path: /ajouter-activité
    controller: App\Controller\ActivitesController::add

show_activies:
    path: /consulter-activités
    controller: App\Controller\ActivitesController::show



# A propos de Ookan -------------------------------------------
mentions:
    path: /mentions-legales
    controller: App\Controller\MentionsController::mentions

contact:
    path: /contactez-nous
    controller: App\Controller\ContactController::contact

qui_sommes_nous:
    path: /qui-sommes-nous
    controller: App\Controller\DefaultController::ookan_team

