index:
    path: /base
    controller: App\Controller\DefaultController::index

connect:
    path: /connexion
    controller: App\Controller\DefaultController::connect

accueil:
    path: /
    controller: App\Controller\AccueilController::index

inscription_phase1:
    path: /inscription/choisissez-votre-profil
    controller: App\Controller\DefaultController::inscription_choix_profil

mentions:
    path: /mentions-legales
    controller: App\Controller\DefaultController::mentions


contact:
    path: /contactez-nous
    controller: App\Controller\DefaultController::contact

les_restos :
    path: /les-restos
    controller: App\Controller\MangerController::manger

les_sorties :
    path: /les-sorties
    controller: App\Controller\SortirController::index

les_activites :
    path: /les-activites
    controller: App\Controller\ActivitesController::index